package com.aceinvoice.generic;

public interface Autoconst
{
	
	
	String APP_URL="https://qa.aceinvoice.com/sign_in";  
	String TEAM_FIRSTNAME="DUMMY FIRSTNAME";
	String TEAM_LASTNAME="DUMMY LASTNAME";
	
	String TEAM_EMAIL="surajb1@example.com";
	String TEAM_PASSWORD="1234567";
	String COMPANYNAME="DUMMY COMPANY";
	
	String  CLIENT_NAME="DUMMY CLIENT NAME";
	String  CLIENT_SECONDARYNAME="DUMMY CLIENT NAME";
	String  CLIENT_ADDRESS1="DUMMY CLIENT ADDRESS1";
	String  CLIENT_ADDRESS2="DUMMY CLIENT ADDRESS2";
	String  CLIENT_CITY="DUMMY CLIENT CITY";
	String  CLIENT_STATE="DUMMY CLIENT STATE";
	String  CLIENT_COUNTRY="DUMMY CLIENT COUNTRY";
	String  CLIENT_ZIPCODE="DUMMY CLIENT ZIPCODE";
	
	
	String PROJECTNAME="DUMMYPROJECT";
}


